Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'bot/commands/**/*.rb'

Style/RegexpLiteral:
  Exclude:
    - 'bot/commands/**/*.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'bot/commands/**/*.rb'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'
